// the fencr command. the instance table (sandboxes) and the tool path
// consts are generated by default.nix at build, beside pkgs/domain.go and
// its covers()
package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
)

// where a grant's use shows: a counter in the sandbox's ruleset, or a verb in the
// egress journal
type Source struct {
	Kind  string
	Value string
}

type Grant struct {
	Text   string
	Source Source
}

type Sandbox struct {
	Name           string
	ID             int
	IP             string
	HostIP         string
	Inbound        []Grant
	Outbound       []Grant
	Unit           string
	CheckpointUnit string
	// the sandbox's egress unit, empty when it has no road out, and whether a
	// credential writes to its journal
	EgressUnit    string
	Credentials   bool
	StateDir      string
	CheckpointDir string
	Image         string
	APISocket     string
	// the host account that reaches this sandbox's sshd and nothing else
	JumpUser string
	// without keys the module writes no Host alias, and a bare name would
	// resolve to whatever else answers to it
	SSH bool
}

type Style struct{ bold, dim, green, red, reset string }

func style() Style {
	info, err := os.Stdout.Stat()
	if err == nil && info.Mode()&os.ModeCharDevice != 0 {
		return Style{"\x1b[1m", "\x1b[2m", "\x1b[32m", "\x1b[31m", "\x1b[0m"}
	}
	return Style{}
}

// the exit status is kept: journalctl uses 1 for "nothing matched"
type cmdError struct {
	reason string
	code   int
}

func (e *cmdError) Error() string { return e.reason }

func output(name string, args ...string) (string, error) {
	var stderr strings.Builder
	command := exec.Command(name, args...)
	command.Stderr = &stderr
	out, err := command.Output()
	if err == nil {
		return string(out), nil
	}
	code := -1
	var exit *exec.ExitError
	if errors.As(err, &exit) {
		code = exit.ExitCode()
	}
	for _, line := range strings.Split(stderr.String(), "\n") {
		if line != "" {
			return "", &cmdError{line, code}
		}
	}
	return "", &cmdError{err.Error(), code}
}

func run(name string, args ...string) {
	command := exec.Command(name, args...)
	command.Stdout, command.Stderr = os.Stdout, os.Stderr
	if err := command.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "fencr: %s %s: %v\n", name, strings.Join(args, " "), err)
		os.Exit(1)
	}
}

func execute(name string, args ...string) {
	err := syscall.Exec(name, append([]string{name}, args...), os.Environ())
	fmt.Fprintf(os.Stderr, "fencr: exec failed: %v\n", err)
	os.Exit(1)
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage: fencr <command> [sandbox-name]")
	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "  list                  declared sandboxes")
	fmt.Fprintln(os.Stderr, "  ssh <sandbox> [cmd]   open a shell (or run a command) in a sandbox")
	fmt.Fprintln(os.Stderr, "                        set FENCR_HOST to reach one from off the host")
	fmt.Fprintln(os.Stderr, "  status [sandbox]      health and traffic [--watch]; --full for systemctl")
	fmt.Fprintln(os.Stderr, "  checkpoint <sandbox> [name]")
	fmt.Fprintln(os.Stderr, "                        copy the sandbox's disk now, without pausing it")
	fmt.Fprintln(os.Stderr, "  checkpoints <sandbox> [--rm <name>]")
	fmt.Fprintln(os.Stderr, "                        list the sandbox's checkpoints, or remove one")
	fmt.Fprintln(os.Stderr, "  restore <sandbox> <name>")
	fmt.Fprintln(os.Stderr, "                        stop the sandbox, replace its disk with the checkpoint, start it")
	os.Exit(1)
}

func arg(args []string, at int) string {
	if at >= len(args) {
		usage()
	}
	return args[at]
}

func find(name string) *Sandbox {
	for at := range sandboxes {
		if sandboxes[at].Name == name {
			return &sandboxes[at]
		}
	}
	fmt.Fprintf(os.Stderr, "fencr: unknown sandbox %q\n", name)
	os.Exit(1)
	return nil
}

func unavailable(reason string, s Style) string {
	return fmt.Sprintf("%sunavailable: %s%s", s.dim, reason, s.reset)
}

func grantSummary(grants []Grant) string {
	if len(grants) == 0 {
		return "denied"
	}
	texts := make([]string, 0, len(grants))
	for _, grant := range grants {
		texts = append(texts, grant.Text)
	}
	return strings.Join(texts, ", ")
}

func printList() {
	fmt.Printf("%-16s %-3s %-12s INBOUND / OUTBOUND\n", "NAME", "ID", "IP")
	for _, sandbox := range sandboxes {
		fmt.Printf("%-16s %-3d %-12s %s / %s\n",
			sandbox.Name, sandbox.ID, sandbox.IP, grantSummary(sandbox.Inbound), grantSummary(sandbox.Outbound))
	}
}

func props(unit, names string) (map[string]string, error) {
	out, err := output(systemctlBin, "show", unit, "--property="+names)
	if err != nil {
		return nil, err
	}
	values := map[string]string{}
	for _, line := range strings.Split(out, "\n") {
		if key, value, ok := strings.Cut(line, "="); ok {
			values[key] = value
		}
	}
	return values, nil
}

func human(bytes uint64) string {
	switch {
	case bytes >= 1<<30:
		return fmt.Sprintf("%.1fG", float64(bytes)/float64(uint64(1)<<30))
	case bytes >= 1<<20:
		return fmt.Sprintf("%dM", bytes>>20)
	default:
		return fmt.Sprintf("%dK", bytes>>10)
	}
}

// the kind out of the firewall's "fencr:<sandbox>:<kind>" tag
func kind(line, name string) (string, bool) {
	_, rest, ok := strings.Cut(line, "fencr:"+name+":")
	if !ok {
		return "", false
	}
	if end := strings.IndexAny(rest, "\":"); end >= 0 {
		return rest[:end], true
	}
	return rest, true
}

func field(line, key string) (string, bool) {
	_, rest, ok := strings.Cut(line, key)
	if !ok {
		return "", false
	}
	if values := strings.Fields(rest); len(values) > 0 {
		return values[0], true
	}
	return "", false
}

func packets(ruleset, name, tag string) uint64 {
	var total uint64
	for _, line := range strings.Split(ruleset, "\n") {
		if found, ok := kind(line, name); !ok || found != tag {
			continue
		}
		value, ok := field(line, "packets ")
		if !ok {
			continue
		}
		if count, err := strconv.ParseUint(value, 10, 64); err == nil {
			total += count
		}
	}
	return total
}

type result struct {
	text string
	err  error
}

// the egress journal: one line per connection, "allow|deny|intercept <host>"
// or "deny: <reason>", and one json record per credential request
func egressLog(sandbox *Sandbox) *result {
	if sandbox.EgressUnit == "" {
		return nil
	}
	text, err := output(journalctlBin,
		"-u", sandbox.EgressUnit, "-q", "-n", "400", "--no-pager", "-o", "cat")
	return &result{text, err}
}

// enough for the proxy's flat access log; no parser worth the dependency
func jsonField(record, key string) (string, bool) {
	at := strings.Index(record, "\""+key+"\":")
	if at < 0 {
		return "", false
	}
	rest := record[at+len(key)+3:]
	if value, quoted := strings.CutPrefix(rest, "\""); quoted {
		if end := strings.Index(value, "\""); end >= 0 {
			return value[:end], true
		}
		return value, true
	}
	if end := strings.IndexAny(rest, ",}"); end >= 0 {
		return rest[:end], true
	}
	return rest, true
}

type counted struct {
	text  string
	count uint64
}

func ranked(hits map[string]uint64) []counted {
	out := make([]counted, 0, len(hits))
	for text, count := range hits {
		out = append(out, counted{text, count})
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].count != out[j].count {
			return out[i].count > out[j].count
		}
		return out[i].text < out[j].text
	})
	return out
}

func requests(log string) []counted {
	hits := map[string]uint64{}
	for _, record := range strings.Split(log, "\n") {
		if !strings.Contains(record, "\"msg\":\"handled request\"") {
			continue
		}
		method, gotMethod := jsonField(record, "method")
		host, gotHost := jsonField(record, "host")
		uri, gotURI := jsonField(record, "uri")
		status, gotStatus := jsonField(record, "status")
		if !gotMethod || !gotHost || !gotURI || !gotStatus {
			continue
		}
		hits[fmt.Sprintf("%s %s%s → %s", method, host, uri, status)]++
	}
	return ranked(hits)
}

func connections(log, verb, pattern string) uint64 {
	var count uint64
	for _, line := range strings.Split(log, "\n") {
		if host, ok := strings.CutPrefix(line, verb); ok && covers(pattern, host) {
			count++
		}
	}
	return count
}

func plural(count uint64, unit string) string {
	if count == 1 {
		return fmt.Sprintf("%d %s", count, unit)
	}
	return fmt.Sprintf("%d %ss", count, unit)
}

func grantLine(grant Grant, count uint64, err error, unit string, s Style) string {
	switch {
	case err != nil:
		return fmt.Sprintf("  · %-40s  %s", grant.Text, unavailable(err.Error(), s))
	case count == 0:
		return fmt.Sprintf("  %s· %-40s  unused%s", s.dim, grant.Text, s.reset)
	default:
		return fmt.Sprintf("  %s✓%s %-40s  %s", s.green, s.reset, grant.Text, plural(count, unit))
	}
}

func grantLines(sandbox *Sandbox, grants []Grant, ruleset result, proxy *result, s Style, out *[]string) {
	if len(grants) == 0 {
		*out = append(*out, "  denied")
		return
	}
	for _, grant := range grants {
		if grant.Source.Kind == "counter" {
			var count uint64
			if ruleset.err == nil {
				count = packets(ruleset.text, sandbox.Name, grant.Source.Value)
			}
			*out = append(*out, grantLine(grant, count, ruleset.err, "packet", s))
			continue
		}
		var verb string
		switch grant.Source.Kind {
		case "domain":
			verb = "allow "
		case "denied":
			verb = "deny "
		case "credential":
			verb = "intercept "
		default:
			*out = append(*out, fmt.Sprintf("  · %-40s  unknown grant source %q",
				grant.Text, grant.Source.Kind))
			continue
		}
		if proxy == nil {
			*out = append(*out, grantLine(grant, 0, errors.New("no egress unit"), "connection", s))
			continue
		}
		var count uint64
		if proxy.err == nil {
			count = connections(proxy.text, verb, grant.Source.Value)
		}
		*out = append(*out, grantLine(grant, count, proxy.err, "connection", s))
	}
}

type blockedHit struct {
	flow, hint string
}

// what was refused, by peer, with the grant that would admit it
func blocked(sandbox *Sandbox, kernel string, proxy *result) []counted {
	hits := map[blockedHit]uint64{}
	for _, line := range strings.Split(kernel, "\n") {
		found, ok := kind(line, sandbox.Name)
		if !ok || !strings.HasSuffix(found, "blocked") {
			continue
		}
		dst, ok := field(line, "DST=")
		if !ok {
			dst = "?"
		}
		// multicast is link chatter (igmp reports, mdns); no grant applies
		leading, _, _ := strings.Cut(dst, ".")
		if octet, err := strconv.Atoi(leading); err == nil && octet >= 224 && octet <= 239 {
			continue
		}
		proto := "?"
		if value, ok := field(line, "PROTO="); ok {
			proto = strings.ToLower(value)
		}
		port, hasPort := field(line, "DPT=")
		// a reply to a connection the host no longer tracks misses ct state
		ephemeral := false
		if number, err := strconv.Atoi(port); hasPort && err == nil && number >= 32768 {
			ephemeral = true
		}
		peer := func(target string) string {
			if hasPort {
				return fmt.Sprintf("%s:%s/%s", target, port, proto)
			}
			return fmt.Sprintf("%s/%s", target, proto)
		}
		var flow, hint string
		switch {
		case found == "connections-blocked":
			flow, hint = "guest → "+peer(dst), "over maxConnections"
		case found == "guest-blocked":
			flow = "host  → " + peer("guest")
			if hasPort {
				hint = "inbound " + port
			}
		case found == "dns-blocked":
			flow = "guest → " + peer(dst)
			hint = fmt.Sprintf("dns is the sandbox's own; grant \"%s:53\" to use this one", dst)
		case found == "host-blocked":
			flow = "guest → " + peer("host")
			switch {
			case port == "53" && dst == sandbox.HostIP:
				hint = "outbound \"internet\" or a domain"
			case hasPort && ephemeral:
				hint = "reply to a connection the host no longer tracks"
			case hasPort && proto == "tcp":
				hint = fmt.Sprintf("outbound \"host:%s\"", port)
			}
		case hasPort && proto == "tcp":
			flow = "guest → " + peer(dst)
			hint = fmt.Sprintf("outbound \"%s:%s\"", dst, port)
		default:
			flow = "guest → " + peer(dst)
		}
		hits[blockedHit{flow, hint}]++
	}
	if proxy != nil && proxy.err == nil {
		for _, line := range strings.Split(proxy.text, "\n") {
			host, ok := strings.CutPrefix(line, "deny ")
			if !ok {
				continue
			}
			hint := fmt.Sprintf("outbound \"%s\"", host)
			for _, grant := range sandbox.Outbound {
				if grant.Source.Kind == "denied" && covers(grant.Source.Value, host) {
					hint = fmt.Sprintf("denied by outbound \"!%s\"", grant.Source.Value)
					break
				}
			}
			hits[blockedHit{fmt.Sprintf("guest → %s:443/tls", host), hint}]++
		}
	}
	keys := make([]blockedHit, 0, len(hits))
	for key := range hits {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if hits[keys[i]] != hits[keys[j]] {
			return hits[keys[i]] > hits[keys[j]]
		}
		if keys[i].flow != keys[j].flow {
			return keys[i].flow < keys[j].flow
		}
		return keys[i].hint < keys[j].hint
	})
	out := make([]counted, 0, len(keys))
	for _, key := range keys {
		out = append(out, counted{
			fmt.Sprintf("%-32s  x%-4d  %s", key.flow, hits[key], key.hint), hits[key],
		})
	}
	return out
}

func unitHealth(values map[string]string, err error, s Style) string {
	if err != nil {
		return unavailable(err.Error(), s)
	}
	if load, ok := values["LoadState"]; !ok || load == "not-found" {
		return s.red + "MISSING" + s.reset
	}
	switch values["ActiveState"] {
	case "active":
		return s.green + "RUNNING" + s.reset
	case "failed":
		return s.red + "FAILED" + s.reset
	default:
		return s.red + "STOPPED" + s.reset
	}
}

func vmmState(sandbox *Sandbox) (string, error) {
	response, err := output(curlBin,
		"--disable", "--silent", "--show-error", "--fail", "--noproxy", "*",
		"--max-time", "2", "--max-filesize", "4096",
		"--unix-socket", sandbox.APISocket, "http://localhost/")
	if err != nil {
		return "", err
	}
	switch state, _ := jsonField(response, "state"); state {
	case "Not started", "Running", "Paused":
		return state, nil
	}
	return "", errors.New("invalid VMM state response")
}

func serviceLines(sandbox *Sandbox, s Style, out *[]string) {
	if sandbox.EgressUnit == "" {
		return
	}
	values, err := props(sandbox.EgressUnit, "LoadState,ActiveState")
	*out = append(*out, "Services: egress "+unitHealth(values, err, s))
}

func kernelLog(started string) (string, error) {
	// bounded either way: under --watch this is re-read every two seconds,
	// and a sandbox that has been up for weeks has a whole boot's worth of lines
	args := []string{"-k", "-q", "--no-pager", "-g", "fencr:", "-o", "cat", "-n", "400"}
	if started != "" {
		args = append(args, "--since", started)
	}
	text, err := output(journalctlBin, args...)
	// journalctl exits 1 when -g matches nothing: no denials, not a failure
	var failure *cmdError
	if errors.As(err, &failure) && failure.code == 1 {
		return "", nil
	}
	return text, err
}

func renderVM(sandbox *Sandbox, ruleset result, s Style, out *[]string) {
	values, err := props(sandbox.Unit, "LoadState,ActiveState,MemoryCurrent,ActiveEnterTimestamp")
	state := unitHealth(values, err, s)
	kernel, kernelErr := kernelLog(values["ActiveEnterTimestamp"])
	memory := ""
	if bytes, parseErr := strconv.ParseUint(values["MemoryCurrent"], 10, 64); parseErr == nil {
		memory = "  memory " + human(bytes)
	}
	*out = append(*out, fmt.Sprintf("%s%s%s  %s  %s%s", s.bold, sandbox.Name, s.reset, state, sandbox.IP, memory))
	if vmm, vmmErr := vmmState(sandbox); vmmErr != nil {
		*out = append(*out, "VMM: "+unavailable(vmmErr.Error(), s))
	} else {
		*out = append(*out, "VMM: "+vmm)
	}
	proxy := egressLog(sandbox)
	*out = append(*out, "Inbound (from host):")
	grantLines(sandbox, sandbox.Inbound, ruleset, proxy, s, out)
	*out = append(*out, "Outbound (otherwise denied):")
	grantLines(sandbox, sandbox.Outbound, ruleset, proxy, s, out)
	*out = append(*out, "")
	// the log rule is capped at 5/second while the drop beside it is not, so
	// a flood is counted far lower than it happened
	*out = append(*out, "Blocked (journal, rate-limited sample):")
	if kernelErr != nil {
		*out = append(*out, "  "+unavailable(kernelErr.Error(), s))
	} else {
		hits := blocked(sandbox, kernel, proxy)
		if len(hits) == 0 {
			*out = append(*out, fmt.Sprintf("  %snone%s", s.dim, s.reset))
		}
		for at, hit := range hits {
			if at == 8 {
				break
			}
			*out = append(*out, fmt.Sprintf("  %s✗%s %s", s.red, s.reset, strings.TrimRight(hit.text, " ")))
		}
	}
	if sandbox.Credentials && proxy != nil {
		*out = append(*out, "")
		*out = append(*out, "Credential requests (journal):")
		if proxy.err != nil {
			*out = append(*out, "  "+unavailable(proxy.err.Error(), s))
		} else {
			hits := requests(proxy.text)
			if len(hits) == 0 {
				*out = append(*out, fmt.Sprintf("  %snone%s", s.dim, s.reset))
			}
			for at, hit := range hits {
				if at == 8 {
					break
				}
				*out = append(*out, fmt.Sprintf("  %-40s  x%d", hit.text, hit.count))
			}
		}
	}
	*out = append(*out, "")
	serviceLines(sandbox, s, out)
	*out = append(*out, "")
}

func render(s Style, only string) []string {
	var out []string
	text, err := output(nftBin, "list", "ruleset")
	ruleset := result{text, err}
	for at := range sandboxes {
		if only == "" || only == sandboxes[at].Name {
			renderVM(&sandboxes[at], ruleset, s, &out)
		}
	}
	return out
}

func show(only string, watch bool) {
	s := style()
	if !watch {
		for _, line := range render(s, only) {
			fmt.Println(line)
		}
		return
	}
	fmt.Print("\x1b[2J")
	for {
		fmt.Print("\x1b[H")
		for _, line := range render(s, only) {
			fmt.Print(line + "\x1b[K\n")
		}
		fmt.Printf("%srefreshing every 2s - ctrl-c to quit%s\x1b[K\x1b[0J", s.dim, s.reset)
		time.Sleep(2 * time.Second)
	}
}

func checkpointName(name string) bool {
	if name == "" {
		return false
	}
	for _, letter := range []byte(name) {
		digit := letter >= '0' && letter <= '9'
		alpha := letter >= 'a' && letter <= 'z' || letter >= 'A' && letter <= 'Z'
		if !digit && !alpha && !strings.ContainsRune("_.-", rune(letter)) {
			return false
		}
	}
	return true
}

func checkpointFile(sandbox *Sandbox, name string) (string, error) {
	if !checkpointName(name) {
		return "", fmt.Errorf("%q is not a checkpoint name", name)
	}
	file := filepath.Join(sandbox.CheckpointDir, name+".img")
	if info, err := os.Stat(file); err == nil && info.Mode().IsRegular() {
		return file, nil
	}
	return "", fmt.Errorf("%s has no checkpoint %q", sandbox.Name, name)
}

type checkpoint struct {
	name    string
	bytes   uint64
	written time.Time
}

// a directory that was never created holds no checkpoints; one this user may
// not read is not the same answer
func checkpoints(sandbox *Sandbox) ([]checkpoint, error) {
	dir := sandbox.CheckpointDir
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var found []checkpoint
	for _, entry := range entries {
		name, ok := strings.CutSuffix(entry.Name(), ".img")
		if !ok {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		var bytes uint64
		if status, ok := info.Sys().(*syscall.Stat_t); ok {
			bytes = uint64(status.Blocks) * 512
		}
		found = append(found, checkpoint{name, bytes, info.ModTime()})
	}
	sort.Slice(found, func(i, j int) bool { return found[i].written.After(found[j].written) })
	return found, nil
}

func printCheckpoints(sandbox *Sandbox) {
	found, err := checkpoints(sandbox)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fencr: %v\n", err)
		os.Exit(1)
	}
	if len(found) == 0 {
		fmt.Printf("%s has no checkpoints\n", sandbox.Name)
	}
	for _, entry := range found {
		seconds := uint64(time.Since(entry.written).Seconds())
		var age string
		switch {
		case seconds < 3600:
			age = fmt.Sprintf("%dm ago", seconds/60)
		case seconds < 86400:
			age = fmt.Sprintf("%dh ago", seconds/3600)
		default:
			age = fmt.Sprintf("%dd ago", seconds/86400)
		}
		fmt.Printf("%-32s  %8s  %s\n", entry.name, human(entry.bytes), age)
	}
}

// btrfs clones only between files whose nodatacow attribute matches, and the
// runner sets it on the image; checkpoint.nix carries it the same way. the
// filesystem comes from the directory, which always exists, so a sandbox that has
// never started is a quiet "nothing to carry" rather than an error
func nodatacow(dir, image string) (bool, error) {
	filesystem, err := output(statBin, "-f", "-c", "%T", dir)
	if err != nil {
		return false, err
	}
	if strings.TrimSpace(filesystem) != "btrfs" {
		return false, nil
	}
	flags, err := output(lsattrBin, "-d", image)
	if err != nil {
		if _, statErr := os.Stat(image); errors.Is(statErr, os.ErrNotExist) {
			return false, nil
		}
		return false, fmt.Errorf("lsattr %s: %w", image, err)
	}
	values := strings.Fields(flags)
	return len(values) > 0 && strings.Contains(values[0], "C"), nil
}

// the copy lands beside the image and replaces it by rename, so a restore
// that runs out of space leaves the sandbox the disk it had. the half-written copy
// goes with it: the run that fails for space is the one that must not leave a
// second image behind
func replace(source, dir, image string) error {
	tmp := image + ".tmp"
	if err := stage(source, dir, image, tmp); err != nil {
		if removed := os.Remove(tmp); removed != nil && !errors.Is(removed, os.ErrNotExist) {
			fmt.Fprintf(os.Stderr, "fencr: %v\n", removed)
		}
		return err
	}
	return os.Rename(tmp, image)
}

func stage(source, dir, image, tmp string) error {
	// a copy that died before the rename left this behind
	if err := os.Remove(tmp); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	// nodatacow only takes on an empty file, so it is set before the copy
	created, err := os.Create(tmp)
	if err != nil {
		return err
	}
	created.Close()
	carry, err := nodatacow(dir, image)
	if err != nil {
		return err
	}
	if carry {
		if _, err := output(chattrBin, "+C", tmp); err != nil {
			return err
		}
	}
	if _, err := output(cpBin,
		"--reflink=auto", "--sparse=always", "--preserve=mode,ownership", source, tmp); err != nil {
		return err
	}
	// a rename reaching the directory before the data would leave the sandbox an
	// image with the new name and the old contents
	written, err := os.Open(tmp)
	if err != nil {
		return err
	}
	defer written.Close()
	return written.Sync()
}

func main() {
	args := os.Args[1:]
	if len(args) == 0 {
		usage()
	}
	switch args[0] {
	case "list":
		printList()
	case "ssh":
		// the module's Host <sandbox> alias carries address, user and host key policy
		name := arg(args, 1)
		sandbox := find(name)
		if !sandbox.SSH {
			fmt.Fprintf(os.Stderr,
				"fencr: %s has no ssh keys; set fencr.adminKeys or fencr.sandboxes.%s.authorizedKeys\n",
				name, name)
			os.Exit(1)
		}
		// away from the host there is no Host alias and no route to the
		// subnet, so the jump is the only way the address means anything
		if host := os.Getenv("FENCR_HOST"); host != "" {
			execute(sshBin, append([]string{
				"-J", sandbox.JumpUser + "@" + host,
				"-o", "StrictHostKeyChecking=accept-new",
				"root@" + sandbox.IP,
			}, args[2:]...)...)
		}
		execute(sshBin, append([]string{sandbox.Name}, args[2:]...)...)
	case "status":
		only := ""
		if len(args) > 1 && !strings.HasPrefix(args[1], "-") {
			only = find(args[1]).Name
		}
		full, watch := false, false
		for _, value := range args {
			full = full || value == "--full"
			watch = watch || value == "--watch"
		}
		if full {
			if only == "" {
				usage()
			}
			sandbox := find(only)
			units := []string{"status", sandbox.Unit}
			if sandbox.EgressUnit != "" {
				units = append(units, sandbox.EgressUnit)
			}
			execute(systemctlBin, append(units, "--no-pager")...)
		}
		show(only, watch)
	case "checkpoint":
		// the unit does the work as the sandbox's user; a bad name is its error
		sandbox := find(arg(args, 1))
		name := "manual"
		if len(args) > 2 {
			name = args[2]
		}
		unit := sandbox.CheckpointUnit + name + ".service"
		if _, err := output(systemctlBin, "start", unit); err != nil {
			fmt.Fprintf(os.Stderr, "fencr: checkpoint failed: %v\n", err)
			if log, logErr := output(journalctlBin,
				"-u", unit, "-q", "-n", "5", "--no-pager", "-o", "cat"); logErr == nil {
				fmt.Fprint(os.Stderr, log)
			}
			os.Exit(1)
		}
		printCheckpoints(sandbox)
	case "checkpoints":
		sandbox := find(arg(args, 1))
		if len(args) < 3 {
			printCheckpoints(sandbox)
			return
		}
		if args[2] != "--rm" {
			usage()
		}
		name := arg(args, 3)
		file, err := checkpointFile(sandbox, name)
		if err == nil {
			err = os.Remove(file)
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "fencr: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("removed %s\n", name)
	case "restore":
		// with onStop the stop leaves a checkpoint of what is replaced
		sandbox := find(arg(args, 1))
		name := arg(args, 2)
		file, err := checkpointFile(sandbox, name)
		if err != nil {
			fmt.Fprintf(os.Stderr, "fencr: %v\n", err)
			os.Exit(1)
		}
		run(systemctlBin, "stop", sandbox.Unit)
		if err := replace(file, sandbox.StateDir, sandbox.Image); err != nil {
			fmt.Fprintf(os.Stderr, "fencr: restore failed, the sandbox keeps its disk: %v\n", err)
			os.Exit(1)
		}
		run(systemctlBin, "start", sandbox.Unit)
		fmt.Printf("%s restored from %s\n", sandbox.Name, name)
	default:
		usage()
	}
}
